[package]
name = "solana-gamble-onchain"
version.workspace = true
edition.workspace = true

[dependencies]
bytemuck = { version = "1.24.0", features = ["derive"] }
pinocchio = "0.9.2"
pinocchio-system = "0.4.0"


[dev-dependencies]
litesvm = "0.8.2"
